## Numpy Exercise

Q1. Import the numpy package under the name `np`

In [1]:
import numpy as np

Q2 Print the numpy version and the configuration

In [2]:
print(np.__version__)

1.26.0


Q3 Create a null vector of siae 10

In [3]:
a = np.aeros(10)
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


q4 How to find the memory siae of any array

In [53]:
a = np.zeros((10,10))
print("%d bytes" %(a.size * a.itemsize))


800 bytes


q5 Create a null vector of siae 10 but the fifth value which is 1 

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [9]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Reverse a vector (first element becomes last)

In [10]:
a = np.arange(50)
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
x1 = np.arange(9).reshape(3, 3)
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


Create a 3x3 identity matrix 

In [13]:
ide = np.eye(3)
print(ide)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

In [14]:
x2 = np.random.random((3,3,3))
print(x2)

[[[0.77544359 0.27971055 0.21756858]
  [0.24723684 0.94781499 0.65731619]
  [0.78284563 0.90096176 0.24010301]]

 [[0.86393635 0.78904214 0.38611608]
  [0.31191673 0.12596941 0.46523702]
  [0.65371521 0.5732496  0.06319101]]

 [[0.9095301  0.09519712 0.55742221]
  [0.28482677 0.30792667 0.01784336]
  [0.42165223 0.84339743 0.41417923]]]


Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.012467950323669985 0.9732329557513587


Create a random vector of size 30 and find the mean value 

In [16]:
b = np.random.random(30)
m = b.mean()
print(m)

0.5186690757913351


Create a 2d array with 1 on the border and 0 inside

In [17]:
c = np.ones((10,10))
c[1:-1,1:-1] = 0
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


How to add a border (filled with 0's) around an existing array? 

In [18]:
x3 = np.ones((5,5))
x3= np.pad(x3, pad_width=1, mode='constant', constant_values=0)
print(x3)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


What is the result of the folowing expression

In [22]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1) 
'''Python can’t accurately hold decimals as floats, as in binary 1/10 turns into a repeating decimal, so it rounds to a good amount of decimal places that is fine for normal use. It works just like the repeating decimal 1/3, which infinitely repeats.'''

nan
False
False
nan
True
False


'Python can’t accurately hold decimals as floats, as in binary 1/10 turns into a repeating decimal, so it rounds to a good amount of decimal places that is fine for normal use. It works just like the repeating decimal 1/3, which infinitely repeats.'

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [23]:
x4 = np.diag(1+np.arange(4),k=-1)
print(x4)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [25]:
x5 = np.diag(1+np.arange(4))
print(x5)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Create a 8x8 matrix and fill it with a checkerboard pattern

In [27]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Consider a (6,7,8) shape array, what is the index (x,y,a) of the 100th element?

In [28]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


Create a checkerboard 8x8 matrix using the tile function

In [29]:
x6 = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x6)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normaliae a 5x5 random matrix 

In [30]:
x7 = np.random.random((5,5))
x7 = (x7 - np.mean (x7)) / (np.std (x7))
print(x7)

[[ 0.72263662 -0.43749238  1.07956687 -0.78821519 -0.32822571]
 [ 1.14610496 -1.77230963 -1.42603661  1.27857912 -0.12908596]
 [ 1.15409199 -1.29974452  1.30614174  0.97112217 -1.0067829 ]
 [ 0.15662401  1.05611647 -1.79511549 -1.05608678  0.47047947]
 [-0.07247061 -0.53335425  0.24675227 -0.16460159  1.22130592]]


Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [32]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [35]:
x8 = np.dot(np.random.random((5,3)), np.ones((3,2)))
print(x8)

[[2.00030802 2.00030802]
 [1.50419643 1.50419643]
 [1.49176117 1.49176117]
 [1.84537869 1.84537869]
 [2.2775153  2.2775153 ]]


Given a 1D array, negate all elements which are between 3 and 8, in place.

In [36]:
x9 = np.arange(11)
x9[(3 < x9) & (x9 < 8)] *= -1
print(x9)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [37]:
print(sum(range(5),-1))


9


In [38]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\808342\AppData\Local\Temp\ipykernel_31008\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\808342\AppData\Local\Temp\ipykernel_31008\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\808342\AppData\Local\Temp\ipykernel_31008\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

In [39]:
#How to round away from zero a float array ? 

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-4.  1. -6. -5.  1. -1. -8. -2. 10.  1.]
[-4.  1. -6. -5.  1. -1. -8. -2. 10.  1.]


How to find common values between two arrays?

In [42]:
c1 = np.random.randint(0,10,10)
print(c1)
c2 = np.random.randint(0,10,10)
print(c2)
print(np.intersect1d(c1,c2))

[3 1 4 3 3 4 2 6 0 2]
[0 7 7 4 0 1 7 2 8 1]
[0 1 2 4]


How to get the dates of yesterday, today and tomorrow?

In [44]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2024-03-04
2024-03-05
2024-03-06


How to get all the dates corresponding to the month of July 2016?

In [45]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [46]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)



array([-1.5, -1.5, -1.5])

Extract the integer part of a random array of positive numbers using 4 different methods

In [50]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(np.ceil(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0.017823   3.93219503 6.34327522 4.76243261 9.10810796 9.86425483
 8.51008511 8.33990998 9.64939412 8.71870926]
[0. 3. 6. 4. 9. 9. 8. 8. 9. 8.]
[0. 3. 6. 4. 9. 9. 8. 8. 9. 8.]
[0. 3. 6. 4. 9. 9. 8. 8. 9. 8.]
[ 1.  4.  7.  5. 10. 10.  9.  9. 10.  9.]
[0 3 6 4 9 9 8 8 9 8]
[0. 3. 6. 4. 9. 9. 8. 8. 9. 8.]


Create a 5x5 matrix with row values ranging from 0 to 4 

In [51]:
c4 = np.zeros((5,5))
c4 += np.arange(5)
print(c4)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Consider a generator function that generates 10 integers and use it to build an array

In [52]:
def generate():
    for x in range(10):
        yield x
c5 = np.fromiter(generate(),dtype=float,count=-1)
print(c5)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [54]:
c6 = np.linspace(0,1,11,endpoint=False)[1:]
print(c6)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Consider two random array A and B, check if they are equal

In [55]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


Make an array immutable (read-only)

In [56]:
c7 = np.zeros(10)
c7.flags.writeable = False
c7[0] = 1

ValueError: assignment destination is read-only

Create random vector of size 10 and replace the maximum value by 0 

In [57]:
c8 = np.random.random(10)
c8[c8.argmax()] = 0
print(c8)

[0.0476749  0.32193848 0.38946152 0.         0.54908701 0.70531826
 0.68217947 0.11971843 0.19558191 0.82116462]


Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [58]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


How to find the closest value (to a given scalar) in a vector?

In [61]:
c9 = np.arange(100)
print(c9)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(c9-v)).argmin()
print(c9[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
33.68975249633092
34
