#Numpy Learnings

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([3,.5,6,78,2])

In [29]:
myarr

array([ 3. ,  0.5,  6. , 78. ,  2. ])

In [30]:
myarr1 = np.array([3,5,6,7],np.int64)
myarr1

array([3, 5, 6, 7], dtype=int64)

In [31]:
myarr1[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [35]:
myarr2 = np.array([[3,5,6,7],[4,2,2,5]],np.int64)
myarr2[0,1],myarr2[1,1]

(5, 2)

In [36]:
myarr2.shape

(2, 4)

In [37]:
myarr2.dtype

dtype('int64')

In [38]:
myarr2[0,1] = 45
myarr2

array([[ 3, 45,  6,  7],
       [ 4,  2,  2,  5]], dtype=int64)

## creating numpy arrays

### Method 1 Conversion from other python structures


In [39]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
listarray.dtype, listarray.shape, listarray.size

(dtype('int32'), (3, 3), 9)

### 2 Method : intrinsic numpy array creation objects (e.g, arange, ones, zeros,etc.)

In [42]:
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
lspace = np.linspace(1,50,12)
lspace


array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

linspace ne 1 se lekr 50 tk ki 12 equally spaced digits di

In [46]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33508506e-307, 6.23037657e-307, 2.22526399e-307],
       [6.23053614e-307, 1.29060871e-306, 6.23055651e-307,
        1.06811422e-306, 3.56043054e-307, 1.37961641e-306],
       [9.45697982e-308, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.60220393e-306, 1.86920057e-306, 1.11261570e-306,
        8.01091099e-307, 8.34445562e-308, 3.91792476e-317]])

np.empty random digits ka 4,6 ka array diya


In [47]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

empty_like lspace ka jjo bi size tha uska ek empty array bna deta hai

In [49]:
ide = np.identity(5)
ide
# gives identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
arr = np.arange(99)
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [52]:
arr.ravel()
# 3,33 converted into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

1d [axis0]
2d [axis0,axis1]

In [53]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar  = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
ar.sum(axis=0)

array([12,  8,  9])

In [55]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [56]:
# Transpose

ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [58]:
# gives all the elements of array
ar.flat

for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [61]:
ar.ndim, ar.size,ar.nbytes

(2, 9, 36)

In [66]:
one = np.array([1,3,4,634,2])

#argsort sorts one d array
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [64]:
# argmin give index of min element
one.argmin()


0

In [65]:
# argmax give index of max element
one.argmax()

3

In [67]:
ar.argmin()

8

In [68]:
ar.argmax()

6

In [73]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [74]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [75]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [76]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [78]:
ar2 = np.array([[3, 9, 1],
       [6, 5, 2],
       [7, 8, 0]])

In [79]:
ar +ar2

array([[ 4, 11,  4],
       [10, 10,  8],
       [14,  9,  0]])

In [80]:
ar * ar2

array([[ 3, 18,  3],
       [24, 25, 12],
       [49,  8,  0]])

In [81]:
np.sqrt(ar2)

array([[1.73205081, 3.        , 1.        ],
       [2.44948974, 2.23606798, 1.41421356],
       [2.64575131, 2.82842712, 0.        ]])

In [82]:
ar.sum()

29

In [83]:
ar.min()

0

In [84]:
ar.max()

7

In [87]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [88]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [89]:
np.where(ar2>5)

(array([0, 1, 2, 2], dtype=int64), array([1, 0, 0, 1], dtype=int64))

In [90]:
ar2

array([[3, 9, 1],
       [6, 5, 2],
       [7, 8, 0]])

In [91]:
np.count_nonzero(ar2)

8

In [92]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [93]:
import sys

In [94]:
py_ar = [0,4,55,2]

In [95]:
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

112

In [96]:
np_ar.itemsize * np_ar.size

16